-- ==========================================
-- Tabela de usuários
-- ==========================================
CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,

    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,

    -- Autenticação em dois fatores (2FA)
    two_factor_enabled BOOLEAN DEFAULT FALSE,
    two_factor_secret VARCHAR(255),

    -- Recuperação de senha
    reset_token VARCHAR(255),
    reset_token_expiration TIMESTAMP,

    -- Proteção contra brute force
    failed_attempts INTEGER DEFAULT 0,
    account_locked BOOLEAN DEFAULT FALSE,
    lock_time TIMESTAMP,

    -- Controle de sessão
    session_token VARCHAR(255),
    session_expiration TIMESTAMP,

    -- Consentimento LGPD
    consent_given BOOLEAN DEFAULT FALSE,
    consent_date TIMESTAMP
);

-- ==========================================
-- Tabela de logs
-- ==========================================
CREATE TABLE logging_event (
    timestmp          BIGINT        NOT NULL,
    formatted_message TEXT          NOT NULL,
    logger_name       VARCHAR(254)  NOT NULL,
    level_string      VARCHAR(254)  NOT NULL,
    thread_name       VARCHAR(254),
    reference_flag    SMALLINT,
    caller_filename   VARCHAR(254),
    caller_class      VARCHAR(254),
    caller_method     VARCHAR(254),
    caller_line       CHAR(4),

    arg0              VARCHAR(254),
    arg1              VARCHAR(254),
    arg2              VARCHAR(254),
    arg3              VARCHAR(254),

    event_id          BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    PRIMARY KEY (event_id)
);

-- ==========================================
-- Propriedades dos eventos de log
-- ==========================================
CREATE TABLE logging_event_property (
    event_id      BIGINT       NOT NULL,
    mapped_key    VARCHAR(254) NOT NULL,
    mapped_value  TEXT,

    PRIMARY KEY (event_id, mapped_key),

    CONSTRAINT fk_logging_event_property
        FOREIGN KEY (event_id)
        REFERENCES logging_event(event_id)
);

-- ==========================================
-- Exceções dos eventos de log
-- ==========================================
CREATE TABLE logging_event_exception (
    event_id    BIGINT       NOT NULL,
    i           SMALLINT     NOT NULL,
    trace_line  VARCHAR(254) NOT NULL,

    PRIMARY KEY (event_id, i),

    CONSTRAINT fk_logging_event_exception
        FOREIGN KEY (event_id)
        REFERENCES logging_event(event_id)
);