# Nome da aplicação Spring Boot
spring.application.name=authdemo

# ============================================================
# CONFIGURAÇÕES DO BANCO DE DADOS (PostgreSQL)
# ============================================================

spring.datasource.url=jdbc:postgresql://<HOST>:<PORTA>/<NOME_DO_BANCO>
spring.datasource.username=<USUARIO_DO_BANCO>
spring.datasource.password=<SENHA_DO_BANCO>

# ============================================================
# CONFIGURAÇÕES DE E-MAIL (SMTP do Gmail)
# ============================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=<EMAIL_REMETENTE>
spring.mail.password=<SENHA_DE_APLICATIVO>

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ============================================================
# CONFIGURAÇÕES DO JPA (Java Persistence API) E HIBERNATE
# ============================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================================================
# TLS/HTTPS
# ============================================================

server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=<SENHA_DO_KEYSTORE>
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=authdemo

# ============================================================
# CRIPTOGRAFIA
# ============================================================

encryption.secret=<CHAVE_DE_CRIPTOGRAFIA>

# ============================================================
# LOGGING
# ============================================================

logging.file.name=logs/auditoria.log
logging.level.com.pfc.suaoficina.authdemo.service.UserService=INFO